language: node_js

node_js:
  - '14'
  - '12'

os:
  - linux
  - osx
  - windows

env:
  global:
    - FORCE_COLOR=1

install:
  - npm install

script:
  - npm test

jobs:
  exclude:
    # https://github.com/Automattic/node-canvas/issues/1626
    - os: osx
      node_js: '14'
  include:
    - stage: test
      os: linux
      node_js: '10'
    - stage: test
      os: osx
      node_js: '8'
    - stage: test
      os: windows
      node_js: '10'
    - stage: test
      os: windows
      node_js: node
    - stage: npm release
      if: tag IS present
      os: linux
      node_js: '12'
      install: skip
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: WDNexbzRQPDYsiZ7nzxsztScbt23U8scCEYJrefZ+T74JWoSakYff8AlA5XNyIjlu0RzXSHqexLAba7vPS91S7akS6oh5RgLzcztOd+N9qyPKuIJpOZesSN+QqOW4v/NigGduCjRUrBGiNusHPFGDPajZxa14A1wJv0yY+KN/WiToy0Gnf2AE84pUCjscrv+ZNs7IiwfzKWCx1JXjaXOIbfr7eWHm9gHPzKBr38SsluxzjLJtLEmed07yw7qRdedK0ITpjPAPiCHKzh5A5juYmhr/fBXNAHPjWr2z0LZWd7FQ8bK1NMg/e0zPsxiuH7OeabC4u8NNcAoN6ES4LPtgWmqMRcUGUOliTHtHmMMOMg0gU11mNxZI2KbAw/JqMxMy6kcViZP5AMdKbqwtWS9vngzSbkucweaXjCigckI/6sOnsTbHZ2l8JVh8ibdoICLy4OFX03K7q/ctZhi+CjcGlgyBAVVeEUe294rF1DnLU2twRGA4YC8MckeuML2xNUBy8oqI/Qfx2551m661wcFD/LK06IDBWSNKiN1p9vPlSil0QOaKDk5vPpeli8TDvlsCt6BFUcaYe86aDexzw/LZcC/nRCBrPkn76DPl6aO74bVPRhQHk31pqc3+3VQb7OaM1q6d8J6Kbta8eRF038qas+mJcjszjSzc1HyWCt/5AU=
        on:
          tags: true
          repo: catdad-experiments/svg-render
