name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: test (${{matrix.os}}, node@${{matrix.node}})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18, 20, 22]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # these are only excluded so we don't run so many jobs
        # they are more expensive and less likely to be a problem if the rest pass
        exclude:
          - os: macOS-latest
            node: 18
          - os: windows-latest
            node: 20
          - os: macOS-latest
            node: 22
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm test
      - name: inspect tarball
        run: npm pack
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
